#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
# This is filtered because it takes too long to display the whole lot
exec > >(grep --binary-files=text "Processed" | tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Extract assets
./tools/torch otr baserom.us.rev1.z64
