#!/bin/bash
# This is autogenerated -- edits will be overwritten

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
get_controls

# Run PMHacks
pmhacks_dir=/$directory/ports/pmhacks/
if [ -f "${pmhacks_dir}/pmhacks.bash" ]; then
  . "${pmhacks_dir}/pmhacks.bash"
fi

. "${0}.pmhacks.orig"
